# Generated by Django 4.0.1 on 2022-01-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.TextField(),
        ),
    ]
