# Generated by Django 4.0.1 on 2022-01-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0003_alter_users_firstname_alter_users_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='firstna',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='lastna',
        ),
    ]
