# Generated by Django 4.0.1 on 2022-01-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0006_alter_user_firstname_alter_user_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
